name: Go files

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    strategy:
      fail-fast: true

    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'

      - name : Run go tests
        run: go test ./...
        id: tests